<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Forgot password</name>
   <tag></tag>
   <elementGuidId>3d1157b2-c11f-45f9-8f12-354b7dff5303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/div[6]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.login-forgot-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1a121dd-df68-4796-9dbc-2b0d249a07ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-forgot-password</value>
      <webElementGuid>407c90a1-5fc2-4994-8597-78b96aa6d4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot password?</value>
      <webElementGuid>37eebf76-cc0c-4038-9c94-a97e2fd2c225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/div[@class=&quot;col-md-12 login-input-text&quot;]/a[1]/span[@class=&quot;login-forgot-password&quot;]</value>
      <webElementGuid>48526b29-68fe-4563-b068-1a729e9a48a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[6]/a/span</value>
      <webElementGuid>9df1678a-4385-4f49-bc07-b8558bdc2571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MERCHANT LOGIN'])[1]/following::span[1]</value>
      <webElementGuid>f6a54c60-8801-4c8a-a18a-b4dd3ecf8926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='please wait'])[2]/following::span[1]</value>
      <webElementGuid>04a37311-72e1-49db-86c1-6cde91294743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='please wait'])[3]/preceding::span[1]</value>
      <webElementGuid>a46c5d36-0176-4a2e-bb0e-2a28ca6156d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot password?']/parent::*</value>
      <webElementGuid>ebdf0ba3-a8bb-4c0f-9ea5-6e3f15a24a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>c22827b3-2daa-432a-9fee-aa60aefc1d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Forgot password?' or . = 'Forgot password?')]</value>
      <webElementGuid>6b84e1a5-8b45-409c-9d03-eb8454668b39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
