<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Mobipaid new UI_fa fa-times fa-2x</name>
   <tag></tag>
   <elementGuidId>8773ae7a-37e8-433e-86f0-a17ae5b4f193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='news1']/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-times.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d357a4f7-8804-4190-b688-8b750627d187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times fa-2x</value>
      <webElementGuid>276f0511-2b52-469f-ad1a-e45cb505a516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b05337b0-58fa-4c99-8cc7-dffb0340d717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;news1&quot;)/div[@class=&quot;news-card&quot;]/div[@class=&quot;close-btn&quot;]/a[@class=&quot;close-walktrough&quot;]/i[@class=&quot;fa fa-times fa-2x&quot;]</value>
      <webElementGuid>73623449-5c77-4c79-9d1a-6e9e3794af97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='news1']/div/div/a/i</value>
      <webElementGuid>1b01eeac-8680-4b21-9ffa-04db2b6d80f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>860ccce7-4c13-4050-96d3-ac747d25e870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
