<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Same as company address_address_same__59d90d</name>
   <tag></tag>
   <elementGuidId>c2e58987-b290-4a3a-a61a-e3c3601ab5e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sameCompanyAddressCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sameCompanyAddressCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdaedd3e-5fd2-4840-b1b2-f07c2f34c2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>aabfdd43-1cee-467a-a22a-05569ec05722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1c1b4d95-f8ca-4efa-abc9-c7e1a149e62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_same_as_company</value>
      <webElementGuid>f423fd1f-ada9-42c9-b134-2fb912cd7a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sameCompanyAddressCheck</value>
      <webElementGuid>0fe511df-c2d1-428b-adbe-be16d3f94ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sameCompanyAddressCheck&quot;)</value>
      <webElementGuid>bdfd0c5b-4a6e-4a6c-ae8d-47a69fb64d92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sameCompanyAddressCheck']</value>
      <webElementGuid>ac038d96-45c4-4637-b2f5-8aac716ccc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[6]/div/div/label/input</value>
      <webElementGuid>e0783e43-bc91-4a5b-a0e7-80e514c6fd3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/label/input</value>
      <webElementGuid>ea57f9ad-dc01-42f3-a13d-e406d99b6765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'address_same_as_company' and @id = 'sameCompanyAddressCheck']</value>
      <webElementGuid>81f5ac60-079f-453a-b6a9-36382f945ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
