<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_signatory_id_number</name>
   <tag></tag>
   <elementGuidId>2f2d543c-e5bd-43f6-b7be-1501451dd38d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputSignatoryIdNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputSignatoryIdNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c1ca3b4-0561-4e3b-9d0d-0c5c62de60c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>f0ba9bc6-eb16-4843-be3a-9e708791361d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2d64a95-a5fe-46bf-9579-0ca6fb0c2569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit error</value>
      <webElementGuid>be65e7c9-855f-403c-b2f1-ecb73f8209f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputSignatoryIdNumber</value>
      <webElementGuid>c7cbada9-9246-4c61-8547-a627c1d62064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_id_number</value>
      <webElementGuid>261b932c-b6f9-40ed-93f7-e6150f1d1b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSignatoryIdNumber&quot;)</value>
      <webElementGuid>2bbcc260-b9f0-4f98-b8c3-bcedbd5bd2e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputSignatoryIdNumber']</value>
      <webElementGuid>f0cc3fd6-7dad-4159-801e-470fe89293b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[4]/div/input</value>
      <webElementGuid>365968d9-63fc-4c1b-b0ed-c1ce2ae20735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a7dc5ae9-897f-4471-9640-8c9db488906b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputSignatoryIdNumber' and @name = 'signatory_id_number']</value>
      <webElementGuid>6ad1a885-7447-4eef-8ed4-d18e8acb0b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
