<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Number_account_number</name>
   <tag></tag>
   <elementGuidId>dc99a815-8aa9-4c72-98f9-f841de4cbd36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_account_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_account_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>147ba94e-196d-46cd-a038-3e244d9fdc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>59551ed9-8b93-4836-a1f0-e62dcacf3f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>476ffb78-3a13-4ec8-b0a9-d9342923ce15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control error</value>
      <webElementGuid>2567ba1b-fb37-45a4-be86-5f58b26ba8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_account_number</value>
      <webElementGuid>8c729b6c-68f1-4cce-b817-fb56feb263e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_number</value>
      <webElementGuid>442f44bf-c87d-477a-bfc4-c2e3dc572a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_account_number&quot;)</value>
      <webElementGuid>70e495d9-859a-4073-8b5d-ac5e1e3f8f40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_account_number']</value>
      <webElementGuid>f6543eaf-367c-416f-a06e-e27619701327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[2]/div[2]/div/input</value>
      <webElementGuid>0628d283-3ce7-4bc9-ae14-e325a7a2bcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>35f469d1-0114-4645-aaea-97b72026eef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_account_number' and @name = 'account_number']</value>
      <webElementGuid>27b06d8f-5c4f-4441-b4aa-8cc91bc75d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
