<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_YES</name>
   <tag></tag>
   <elementGuidId>00c47518-aa6c-4768-8202-a5355b6716e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='send-docs-via-email-field']/div/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.switch-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a080533-68a3-4c9c-8944-1d637841a8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch-left</value>
      <webElementGuid>fd4aead2-5560-4403-abe5-66a69f4fdad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YES</value>
      <webElementGuid>f7b037fe-0397-48ba-88ce-2b49f5334761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send-docs-via-email-field&quot;)/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;switch has-switches&quot;]/div[@class=&quot;switch-on&quot;]/div[@class=&quot;switch has-switches&quot;]/div[@class=&quot;switch-on switch-animate&quot;]/span[@class=&quot;switch-left&quot;]</value>
      <webElementGuid>9fc3e6da-957f-4092-bbc7-166ecd4b78bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='send-docs-via-email-field']/div/div/div/div/div/span</value>
      <webElementGuid>bf0ac127-3d76-487c-96d1-34f618284822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send documents via email'])[1]/following::span[1]</value>
      <webElementGuid>16fd1fce-7066-44f1-aa04-cfee69156201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Required Documents'])[2]/following::span[1]</value>
      <webElementGuid>76f152ea-f0f3-4f53-816f-702912d6b6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::span[1]</value>
      <webElementGuid>d93168b5-5f9a-4a8f-b638-92aca14fca58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/preceding::span[2]</value>
      <webElementGuid>7b9ecbaf-962a-4f00-9498-3931a58a5a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='YES']/parent::*</value>
      <webElementGuid>16bd37b6-2fed-431d-9f4c-235cee5ce50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span</value>
      <webElementGuid>0bc98ee4-37ed-4dca-9310-0759fe291480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'YES' or . = 'YES')]</value>
      <webElementGuid>18ec9288-889f-4025-a7c6-27231675ab88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
