<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NO</name>
   <tag></tag>
   <elementGuidId>be48b57b-59ce-4298-9158-af5e588cadab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='send-docs-via-email-field']/div/div/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.switch-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>527b50d8-b44a-4eb0-932b-30ffad326d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch-right</value>
      <webElementGuid>49f4435e-877a-4375-b879-2e90d6ccc6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>736a400b-eee2-4a4e-a88a-5e8fc0726c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send-docs-via-email-field&quot;)/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;switch has-switches&quot;]/div[@class=&quot;switch-on&quot;]/div[@class=&quot;switch has-switches&quot;]/div[@class=&quot;switch-animate switch-off&quot;]/span[@class=&quot;switch-right&quot;]</value>
      <webElementGuid>c70ab1c5-0461-4b57-b52b-b4658a817e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='send-docs-via-email-field']/div/div/div/div/div/span[2]</value>
      <webElementGuid>cd730705-e6e1-497a-93f7-217a1ee2e119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[1]/following::span[1]</value>
      <webElementGuid>49448d05-956b-438e-b21d-2bfd2b2ef794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send documents via email'])[1]/following::span[2]</value>
      <webElementGuid>8a4eaefa-68fb-4389-ad86-364b4b135653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/preceding::span[1]</value>
      <webElementGuid>3d1982e6-999b-455e-9fe4-dd5fd0208e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/preceding::span[2]</value>
      <webElementGuid>ce4572dd-82cd-44c6-9c59-644e370eba39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NO']/parent::*</value>
      <webElementGuid>8fbb735a-f542-4b84-ab10-1f76be40b55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span[2]</value>
      <webElementGuid>d3df8343-cb2e-45f4-a108-5981ec11c5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NO' or . = 'NO')]</value>
      <webElementGuid>1dfc5c46-ee55-4062-938d-706dc79ad9f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
